apiVersion: v1
kind: Service
metadata:
  name: BoundedContext583.6734693877551
  labels:
    app: BoundedContext583.6734693877551
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext583.6734693877551