apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderMgmt
  labels:
    app: OrderMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderMgmt
  template:
    metadata:
      labels:
        app: OrderMgmt
    spec:
      containers:
        - name: OrderMgmt
          image: username/OrderMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5