apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerService
  labels:
    app: CustomerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerService
  template:
    metadata:
      labels:
        app: CustomerService
    spec:
      containers:
        - name: CustomerService
          image: username/CustomerService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5