apiVersion: apps/v1
kind: Deployment
metadata:
  name: PaymentMgmt
  labels:
    app: PaymentMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentMgmt
  template:
    metadata:
      labels:
        app: PaymentMgmt
    spec:
      containers:
        - name: PaymentMgmt
          image: username/PaymentMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5