apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext223
  labels:
    app: BoundedContext223
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext223
  template:
    metadata:
      labels:
        app: BoundedContext223
    spec:
      containers:
        - name: BoundedContext223
          image: username/BoundedContext223:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5