apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliveryMgmt
  labels:
    app: DeliveryMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliveryMgmt
  template:
    metadata:
      labels:
        app: DeliveryMgmt
    spec:
      containers:
        - name: DeliveryMgmt
          image: username/DeliveryMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5